version: '3.9'

services:
  evidently_app:
    build:
      context: dashboards
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - FLASK_APP=evidently_app.py
    volumes:
      - ./dashboards:/app
    restart: on-failure

  streamlit_app:
    build:
      context: streamlit
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - STREAMLIT_SERVER_PORT=80
    volumes:
      - ./models:/models
      - ./streamlit:/app
    restart: on-failure

  # prefect:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: "prefect orion start --host=0.0.0.0"
  #   volumes:
  #     - ./:/app/
  #   expose:
  #     - "4200"
  #   ports:
  #     - "127.0.0.1:4200:4200"
  #   restart: on-failure
